### ISSUE TITLE
0.2.10.9 - Missing Method

### ISSUE THREAD

**Issue by Fingersniffer** [SEModCommunity/SE-Community-Mod-API#156]
Finished loading LogManager
Finished loading SandboxGameAssemblyWrapper
All main types passed reflection unit tests!
All entity types passed reflection unit tests!
2014-09-13 03:18:03.988 - Failed to find method 'AC280CA879823319A66F3C71D647829
7' in type '5BCAC68007431E61367F5B2CF24E2D6F.12BACAB3471C8707CE7420AE0465548C'
ShipControllerEntity reflection validation failed!
Finished creating server!
Finished loading ServerAssemblyWrapper
Finished loading PluginManager
Finished loading FactionsManager
Finished loading EntityEventManager
Finished loading ChatManager

**Comment by Tyrsis** [comment]
To fix this:

PilotEntity got moved from MyObjectBuilder_ShipController to MyOjbectBuilder_Cockpit.

In CockpitEntity.cs add:
        public static string CockpitGetPilotEntityMethod = "7B47C9D59A1CEE8DA64A258449704EF8";
        public static string CockpitSetPilotEntityMethod = "1BB7956FA537A66315E07C562677018A";

Then move the PilotEntity from ShipController to Cockpit.  

This will not only fix the error, but make PilotEntity usable again.  (which is required for almost all my plugins)

**Comment by generalwrex** [comment]
Seems i did a cheater way to do this in my fork

https://github.com/generalwrex/SE-Community-Mod-API/blob/137b134314f4c1049cbb8cb6398fa41b9c12c1cb/SEModAPIInternal/API/Entity/Sector/SectorObject/CubeGrid/CubeBlock/ShipControllerEntity.cs

line 56

I believe it needs to be moved into the CockpitEntity.cs as well too

i added you on steam Moustachauve, i'm very involved in sese's progress, since without SESe nothing on our server would function =P

If you need my fork for something let me know, otherwise im going to revert it back to the main repo

**Comment by Moustachauve** [comment]
It should be fixed now, I moved it in the CockpitEntity as suggested. Can you test if your plugin works with the please?

**Comment by Tyrsis** [comment]
Change property categories as well, and that looks ok (even though they don't do much):
[Category("Ship Controller")]

to

[Category("Cockpit")]

**Comment by Moustachauve** [comment]
Thank you for your help!
