### ISSUE TITLE
Request: Do not overwrite Log files on relaunch.

### ISSUE THREAD

**Issue by NeoSword** [SEModCommunity/SE-Community-Mod-API#81]
Files in C:\ProgramData\SpaceEngineersDedicated\Instance are overwritten on every server launch. I wanted to provide log files of an issue where deletion of a cube grid in 'sector objects'  or using 'clear floating objects' caused server to shutdown. Unfortunately I wanted to get my server back up ASAP.

Can you append to these logs or if you feel they will grow to large, keep the last X lines of the log on relaunch.

**Comment by DraygoKorvan** [comment]
maybe one way to handle it is to append a datestamp to the logfile name, and only keep the 5 most recent log files.

I know chessmaster knows about the floatingobject crash and that's on his todo, not sure about the cube grid deletion crash.

**Comment by chessmaster42** [comment]
This is mostly complete now. I can't do anything about the default server log but all of the other logs are now using a new logging system that mostly mimics the games logging. The main difference is that some logs will be in the world instance folder as before but others will be in /Logs/ where the SEServerExtender.exe is. All of these logs are now auto-archiving and will rename the old log with the time it was last modified and then create the new log file. It does not handle cleanup of these logs in any way so that will be up to the server operator.
